/**
 * `dsh-usage` — the DeepSeek credit balance, in the TUI status line.
 *
 *     bal:$4.65 (2m)
 *
 * That is the whole plugin. It is deliberately this small: the TUI already
 * renders tokens, cache hit rate and context occupancy from its own token
 * meter (`cache` and `contextUsage` are on by default; `tokens`, `tps` and
 * `contextBar` are one setting away), and it ships a `/tokens` command. The
 * one thing nothing in the harness does is ask the account how much credit is
 * left, because that is an HTTP call rather than anything in the session log.
 *
 * There is no slash command. Plugin-registered commands reach the TUI through
 * `channel.notify()`, whose text is whitespace-collapsed to a single line,
 * capped at 200 cells and rendered in the narrow footer slot — so a report
 * cannot render through that seam, and a one-line one would only repeat the
 * status line.
 *
 * No cost figure either: `/user/balance` reports whole cents ("4.65") while a
 * session routinely costs a fraction of one, and pricing tokens locally would
 * mean hard-coding DeepSeek's peak/off-peak rate tables and windows. The
 * balance is exact and it is the number that answers "can I keep going".
 *
 * ## Why `tuiStatus` is injected rather than soft-probed
 *
 * It has to be. Rows load concurrently, so this one can activate before the
 * `dsh-tui-extensions` row has provided `tuiStatus` — and picking the service
 * up later, from an `internal/service` listener, produces a status line that
 * silently never renders. `tuiStatus.set` runs `requirePluginCaller`, which
 * walks dsh-tui's canonical fiber maps; a row that activated before the
 * service existed fails that check ("mutated runner") and every `set` returns
 * a no-op, warning only to a logger the TUI discards.
 *
 * Declaring the injection makes Cordis defer this row until `tuiStatus` is
 * live, so the first paint happens inside a clean activation and later
 * repaints are accepted too. The cost is that the row stays PENDING under
 * headless/web, which is correct: it has nothing to contribute there.
 */

export const name = 'dsh-usage';

/**
 * Required, not optional — see above. Without it the row loads everywhere and
 * works nowhere.
 */
export const inject = ['tuiStatus'];

const BALANCE_PATH = '/user/balance';
/**
 * The status line is repainted on this cadence so the "(2m)" ages in place.
 * Without it the age would only ever advance at poll time and so would always
 * read "now" — and a failing refresh would look identical to a fresh one.
 * The same tick drives the poll, so the plugin owns exactly one timer.
 */
const TICK_MS = 60_000;

export const DEFAULTS = Object.freeze({
  apiKeyEnv: 'DEEPSEEK_API_KEY',
  baseUrl: 'https://api.deepseek.com',
  /** Which `balance_infos` entry to prefer. */
  currency: 'USD',
  /** Minutes between balance reads. */
  refreshMinutes: 5,
  /** Seconds before a balance request is abandoned. */
  timeoutSeconds: 10,
  /** Status-line key this row owns; plugin-namespaced by convention. */
  statusKey: 'deepseek-usage',
});

// --------------------------------------------------------------- config

/**
 * The config comes from a profile patch written by hand or generated by Nix,
 * so every field is untrusted: a bad value falls back to its default rather
 * than failing the row. A broken balance indicator must never be able to stop
 * the harness from booting.
 */
export function resolveConfig(raw = {}, env = {}) {
  const input = raw === null || typeof raw !== 'object' ? {} : raw;
  const apiKeyEnv = str(input.apiKeyEnv, DEFAULTS.apiKeyEnv);

  return {
    apiKeyEnv,
    // An inline key wins so a one-off override works, but the environment is
    // the intended path: a profile patch is world-readable in /nix/store.
    apiKey: str(input.apiKey, undefined) ?? str(env?.[apiKeyEnv], undefined),
    baseUrl: str(input.baseUrl, DEFAULTS.baseUrl),
    currency: str(input.currency, DEFAULTS.currency).toUpperCase(),
    refreshMs: int(input.refreshMinutes, DEFAULTS.refreshMinutes, 1, 24 * 60) * 60_000,
    timeoutMs: int(input.timeoutSeconds, DEFAULTS.timeoutSeconds, 1, 120) * 1000,
    statusKey: str(input.statusKey, DEFAULTS.statusKey),
  };
}

function str(value, fallback) {
  return typeof value === 'string' && value.trim() !== '' ? value.trim() : fallback;
}

/** Clamp rather than reject: a typo'd interval should not disable the row. */
function int(value, fallback, min, max) {
  if (typeof value !== 'number' || !Number.isFinite(value)) return fallback;
  return Math.min(max, Math.max(min, Math.round(value)));
}

// -------------------------------------------------------------- balance

/**
 * Client for `GET /user/balance`, the only account-level endpoint DeepSeek
 * publishes. Never throws, never hangs, and never puts the credential into an
 * error string.
 */
export function createBalanceClient({
  apiKey,
  baseUrl = DEFAULTS.baseUrl,
  currency = DEFAULTS.currency,
  fetchImpl = globalThis.fetch,
  timeoutMs = 10_000,
} = {}) {
  const endpoint = `${String(baseUrl).replace(/\/+$/, '')}${BALANCE_PATH}`;
  const redact = redactor(apiKey);

  return {
    endpoint,
    async fetchBalance() {
      if (typeof apiKey !== 'string' || apiKey.trim() === '') {
        return { ok: false, error: 'no API key configured' };
      }
      if (typeof fetchImpl !== 'function') {
        return { ok: false, error: 'no fetch implementation available' };
      }

      const controller = new AbortController();
      let timer;
      try {
        // The race is the real guard. Passing the signal too lets a
        // well-behaved fetch close the socket, but a fetch that ignores it
        // still cannot wedge the status line.
        const timeout = new Promise((_, reject) => {
          timer = setTimeout(() => {
            controller.abort();
            reject(new Error(`timed out after ${timeoutMs}ms`));
          }, timeoutMs);
        });

        const response = await Promise.race([
          fetchImpl(endpoint, {
            method: 'GET',
            headers: { Authorization: `Bearer ${apiKey}`, Accept: 'application/json' },
            signal: controller.signal,
          }),
          timeout,
        ]);

        if (!response?.ok) return { ok: false, error: `HTTP ${response?.status ?? 'error'}` };

        const balance = selectBalance(await response.json(), currency);
        return balance === undefined
          ? { ok: false, error: 'response carried no usable balance' }
          : { ok: true, balance };
      } catch (error) {
        return { ok: false, error: redact(error instanceof Error ? error.message : String(error)) };
      } finally {
        clearTimeout(timer);
      }
    },
  };
}

/**
 * Prefer the configured currency, falling back to the first entry the account
 * reports — a CNY-only account should still see its balance.
 */
function selectBalance(body, currency) {
  const entries = body?.balance_infos;
  if (!Array.isArray(entries) || entries.length === 0) return undefined;

  const wanted = String(currency).toUpperCase();
  const entry = entries.find((item) => String(item?.currency).toUpperCase() === wanted) ?? entries[0];

  const total = amount(entry?.total_balance);
  if (total === undefined) return undefined;

  return {
    total,
    currency: typeof entry?.currency === 'string' ? entry.currency : undefined,
    available: typeof body.is_available === 'boolean' ? body.is_available : undefined,
  };
}

/** The API returns decimal strings; accept a bare number too. */
function amount(value) {
  if (typeof value === 'number') return Number.isFinite(value) ? value : undefined;
  if (typeof value !== 'string' || value.trim() === '') return undefined;
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : undefined;
}

/** Scrub the credential from anything that could reach a log line. */
function redactor(apiKey) {
  return (text) => {
    let out = text;
    if (typeof apiKey === 'string' && apiKey.length >= 8) out = out.split(apiKey).join('***');
    return out.replace(/\bsk-[A-Za-z0-9._-]{4,}/g, '***');
  };
}

// ------------------------------------------------------------ rendering

/**
 * Two decimals, because that is the precision `/user/balance` actually
 * reports — more would imply a resolution the source does not have.
 */
export function money(value, currency = 'USD') {
  if (typeof value !== 'number' || !Number.isFinite(value)) return '—';
  const [whole, fraction] = Math.abs(value).toFixed(2).split('.');
  const body = `${value < 0 ? '-' : ''}${whole.replace(/\B(?=(\d{3})+$)/g, ',')}.${fraction}`;
  return currency === 'USD' ? `$${body}` : `${body} ${currency}`;
}

/** Compact age, minute granularity — the tick repaints no faster than that. */
export function age(ms) {
  if (typeof ms !== 'number' || !Number.isFinite(ms) || ms < 0) return undefined;
  const minutes = Math.floor(ms / 60_000);
  if (minutes < 1) return 'now';
  if (minutes < 60) return `${minutes}m`;
  const hours = Math.floor(minutes / 60);
  return hours < 24 ? `${hours}h` : `${Math.floor(hours / 24)}d`;
}

/**
 * `bal:$4.65 (2m)`.
 *
 * The age is the staleness signal: a failing refresh keeps the last known
 * figure — still the best answer available — while the age visibly outgrows
 * the poll interval. So there is no separate error marker to decode.
 *
 * Before the first successful read the line is empty rather than a bare
 * label, except when the balance has never been readable at all, which is
 * worth saying out loud.
 */
export function formatStatusLine({ balance, balanceAt, balanceError } = {}, at = Date.now()) {
  if (balance === undefined) return balanceError === undefined ? '' : 'bal:—';
  const since = age(at - balanceAt);
  return `bal:${money(balance.total, balance.currency ?? 'USD')}${since === undefined ? '' : ` (${since})`}`;
}

// ---------------------------------------------------------------- meter

/**
 * Holds the last reading and drives the single tick. No Cordis in here: the
 * balance client is duck-typed, so this is testable with a plain fake.
 */
export function createMeter({
  balanceClient,
  refreshMs = 5 * 60_000,
  onError = () => {},
  now = () => Date.now(),
  setTimer = setInterval,
  clearTimer = clearInterval,
} = {}) {
  let balance;
  let balanceAt;
  let balanceError;
  let lastPollAt;
  let timer;
  let inFlight;
  const listeners = new Set();

  const notify = () => {
    for (const listener of listeners) {
      try {
        listener();
      } catch (error) {
        onError(error);
      }
    }
  };

  /**
   * Never rejects, and never runs concurrently with itself. A failure keeps
   * the previous figure: a stale balance is far more useful than a blank one.
   */
  async function refresh() {
    if (inFlight !== undefined) return inFlight;
    lastPollAt = now();
    inFlight = (async () => {
      try {
        const result = await balanceClient.fetchBalance();
        if (result?.ok) {
          balance = result.balance;
          balanceAt = now();
          balanceError = undefined;
        } else {
          balanceError = result?.error ?? 'balance unavailable';
        }
      } catch (error) {
        // fetchBalance is documented never to throw; belt and braces.
        balanceError = 'balance unavailable';
        onError(error);
      } finally {
        inFlight = undefined;
      }
      notify();
    })();
    return inFlight;
  }

  return {
    refresh,
    snapshot: () => ({ balance, balanceAt, balanceError }),
    onChange(listener) {
      listeners.add(listener);
      return () => listeners.delete(listener);
    },
    start() {
      if (timer !== undefined) return;
      void refresh();
      timer = setTimer(() => {
        // Repaint every tick so the age advances; poll only when due.
        if (now() - (lastPollAt ?? 0) >= refreshMs) void refresh();
        else notify();
      }, TICK_MS);
      // Never hold the process open for a balance indicator.
      timer?.unref?.();
    },
    stop() {
      if (timer === undefined) return;
      clearTimer(timer);
      timer = undefined;
    },
  };
}

// --------------------------------------------------------------- wiring

export async function apply(ctx, entry) {
  const config = resolveConfig(entry, process.env);
  const onError = (error) => ctx.logger?.warn?.(`dsh-usage: ${describe(error)}`);

  const meter = createMeter({
    onError,
    refreshMs: config.refreshMs,
    balanceClient: createBalanceClient({
      apiKey: config.apiKey,
      baseUrl: config.baseUrl,
      currency: config.currency,
      timeoutMs: config.timeoutMs,
    }),
  });

  let clear;

  // `set` returns a disposer that only clears while the key still holds that
  // exact write, so repainting is just calling `set` again and the previous
  // paint's disposer is inert. The third argument is the identity hint: it
  // records this row as the author rather than `undeclared`.
  const paint = () => {
    clear = ctx.tuiStatus.set(config.statusKey, formatStatusLine(meter.snapshot()), ctx);
  };

  // Painting here, synchronously in apply, is what makes the contribution
  // stick: this is the activation dsh-tui's caller guard recognises.
  paint();
  const unsubscribe = meter.onChange(paint);
  meter.start();

  let disposed = false;
  return () => {
    if (disposed) return;
    disposed = true;
    meter.stop();
    for (const dispose of [unsubscribe, clear]) {
      try {
        dispose?.();
      } catch (error) {
        onError(error);
      }
    }
  };
}

function describe(error) {
  return error instanceof Error ? (error.stack ?? error.message) : String(error);
}
