{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.apps.dsh;

  # Kept in step with ../claude-code/cronometer: the same pinned PyPI server,
  # run through uvx against nixpkgs' Python so uv never downloads its own.
  cronometer-mcp-version = "0.2.1";

  settingsFormat = pkgs.formats.yaml { };

  # $DSH_HOME/settings.yaml is mutable state the web UI owns, so this is a
  # merge rather than a copy: `select(fileIndex == 0) * select(fileIndex == 1)`
  # deep-merges the declared file over the live one, so a key nobody declared
  # here (ui-onboarding.welcomeNoticeVersion, anything set from a settings page)
  # survives every rebuild while declared keys are restored.
  dshHome =
    if config.programs.dsh.home != null then
      config.programs.dsh.home
    else
      "${config.home.homeDirectory}/.dsh";

  settingsFile = settingsFormat.generate "dsh-settings.yaml" cfg.settings;

  # Built from ../claude-code's scripts rather than relying on that module
  # having put them on PATH. Same name, same inputs, same text, so Nix resolves
  # these to the very store paths apps.claude-code already builds -- the coach
  # skill keeps working even if claude-code is switched off.
  weather = pkgs.writeShellApplication {
    name = "weather";
    runtimeInputs = with pkgs; [
      curl
      jq
      coreutils
      util-linux
    ];
    text = builtins.readFile ./../claude-code/weather/weather.sh;
  };

  intervals-icu = pkgs.writeShellApplication {
    name = "intervals-icu";
    runtimeInputs = with pkgs; [
      curl
      jq
      coreutils
    ];
    text = builtins.readFile ./../claude-code/intervals-icu.sh;
  };

  # Skills are plain SKILL.md directories, so the whole tree goes to the store
  # and dsh scans it read-only. dsh's own command registry is programmatic
  # (ctx.commands.register, from a plugin) and has no markdown loader, so the
  # claude-code `/coach` command ports to a skill rather than a command.
  skills = ./skills;

  # The declarative seam, now owned by deepseek-harness.nix. A profile composes
  # as: base layer, then the profile's bundles in list order, then this string
  # as the profile's cordis.patch.yml. Nothing is passed at launch any more --
  # the module materializes $DSH_HOME/profiles/nix-<name> from the store and
  # re-syncs it on every activation and every `dsh` run (mode = "managed").
  #
  # This has to be a *profile* patch rather than programs.dsh.patch: the
  # home-level option is typed `listOf attrs` and renders through
  # lib.generators.toYAML, which would quote the `!!js` tags below into inert
  # strings. The profile option also accepts `lines`, and renderPatch passes a
  # string through verbatim, so the tags survive.
  #
  # Two shapes are in play, both verified against --dump-config: a bare `id:`
  # row patches the entry that already exists under that id, and an `insert:`
  # list adds new ones. A patch REPLACES the targeted row's whole `config`, so
  # any row touched here restates every key it means to keep.
  cordisPatch = ''
    # Generated by home/programs/dsh/default.nix -- do not edit in place.

    # The skills system ships disabled in the web profile. tool-skill is the
    # model-facing loader; without it the catalogue is never readable. The tui
    # bundle enables both itself, but this layer applies after it, so stating
    # them here keeps all three profiles identical.
    - id: skill-filesystem
      disabled: false
      config:
        customSkillDirs:
          - ${skills}
    - id: tool-skill
      disabled: false

    # The AGENTS.md/CLAUDE.md workspace loader. Enabled in dsh-base, but the
    # tui bundle turns it off (dsh-tui/cordis.patch.yml:56), so the TUI would
    # otherwise see no project instruction files at all while headless does.
    # It walks the ancestor chain upward from the session workspace rather than
    # reading only the root, so per-project files are picked up the way
    # claude-code does it. maxBytes is restated because a patch replaces the
    # targeted row's whole config.
    - id: agent-instructions
      disabled: false
      config:
        maxBytes: 65536

    # Claude as a model route. pi-ai (the multi-provider layer under
    # dsh-llm-pi-ai) bundles @anthropic-ai/sdk and ships anthropic in its
    # installed catalog, so the route needs no baseURL, protocol or model list
    # -- only where to find the credential. There is no claude-code subagent
    # provider in 0.1.1-rc.2, so this is what "Claude in dsh" means today.
    #
    # Qwen3.8-27B through Qwen Cloud, which is a front end over DashScope
    # International -- hence the aliyuncs endpoint. Deliberately NOT the
    # openrouter route: pi-ai ships openrouter, but the compat gate withholds
    # openRouterRouting, so nothing can pin which of its eleven upstreams
    # serves a request. That means an unknown quantization and an unknown
    # context ceiling per call, which is the wrong footing for judging whether
    # this model is worth keeping. Official costs ~18% more ($0.50/$3.00
    # against $0.35/$2.75) and answers with the reference weights at 1M.
    #
    # pi-ai 0.82.1 ships no `qwen-cloud` provider, and its nearest route
    # (qwen-token-plan) points somewhere else entirely
    # (token-plan.ap-southeast-1.maas.aliyuncs.com), so this route declares the
    # whole provider: endpoint and wire protocol included. Being off-catalog is
    # the upside -- per dsh-llm-pi-ai's discovery.d.ts, "fetch available
    # models" only interrogates a route the catalog does NOT ship, so this one
    # can actually be probed from the web UI, while an openrouter route would
    # answer from its bundled Qwen3.6-era list.
    #
    # Two model fields are load-bearing because a hand-declared model defaults
    # to neither: `input` (the route default is [text], which would leave the
    # vision encoder unreachable) and `reasoningEfforts` (absent means "does
    # not reason", and thinking mode is the reason to run this model). "off" is
    # quoted because a bare `off` is a YAML 1.1 boolean.
    #
    # maxTokensField and supportsUsageInStreaming are stated rather than left
    # to pi-ai, which for an endpoint it does not recognize answers as though
    # it were OpenAI itself -- wrong for most OpenAI-compatible gateways.
    #
    # Qwen Cloud's built-in tools (code_interpreter, web_search, ...) are
    # Responses-API-only server-side tools and are not reachable over
    # openai-completions. That costs nothing: dsh's own web_search runs through
    # the `web` service against DEEPSEEK_API_KEY, independent of whichever
    # model is serving chat, so it keeps working unchanged under this route.
    #
    # The key is region-bound and the name does not say so. Model Studio keys
    # only authenticate against the region that issued them (a mismatch is 401
    # invalid_api_key), and catalogs differ per region -- verified 2026-08-28,
    # Frankfurt serves qwen3.8-max but NOT this model, Singapore serves both.
    # So `dashscope-api-key` is specifically the SINGAPORE key, and adding a
    # second region later means a second secret rather than replacing this one.
    #
    # baseURL is the shared Singapore endpoint rather than the workspace-scoped
    # ws-<id>.ap-southeast-1.maas.aliyuncs.com form. Both serve this model.
    # Alibaba documents the workspace form as the newer path with better
    # stability and is steering away from the shared domains, so this may want
    # revisiting; it is a one-line change, and the only cost is putting the
    # workspace id into a world-readable /nix/store file.
    #
    # The UI writes provider settings into $DSH_HOME/settings.yaml, which
    # resolves ON TOP of this, so adding routes by hand there still works. A
    # missing key surfaces per request as MISSING_CREDENTIAL rather than
    # failing the boot.
    - id: llm-pi-ai
      config:
        providers:
          anthropic:
            apiKeyEnv: ANTHROPIC_API_KEY
          qwen-cloud:
            apiKeyEnv: DASHSCOPE_API_KEY
            displayName: Qwen Cloud
            api: openai-completions
            baseURL: https://dashscope-intl.aliyuncs.com/compatible-mode/v1
            models:
              - id: qwen3.8-27b
                name: Qwen3.8 27B
                contextWindow: 1000000
                maxTokens: 131072
                input:
                  - text
                  - image
                reasoningEfforts:
                  "off": null
                  low: low
                  medium: medium
                  high: high
                compat:
                  thinkingFormat: qwen
                  maxTokensField: max_tokens
                  supportsUsageInStreaming: true
                  # pi-ai sends the system prompt under the `developer` role to
                  # any model that declares reasoning, which this one does.
                  # DashScope answers 400: "developer is not one of ['system',
                  # 'assistant', 'user', 'tool', 'function']". false keeps
                  # `system`. Probed 2026-08-28: developer is the ONLY field of
                  # the OpenAI-shaped set this endpoint rejects -- store,
                  # reasoning_effort, max_completion_tokens and strict tools
                  # are all accepted.
                  supportsDeveloperRole: false

    - insert:
        # Cronometer, mirroring ../claude-code/cronometer. Credentials arrive as
        # process env from the session (see programs.bash.initExtra below)
        # rather than being written here: this file is world-readable in
        # /nix/store.
        - id: mcp-cronometer
          name: '@deepseek-ai/dsh-mcp-client'
          config:
            serverName: cronometer
            transport: stdio
            command: ${lib.getExe' pkgs.uv "uvx"}
            args:
              - '--python'
              - '${pkgs.python314}/bin/python3'
              - 'cronometer-api-mcp==${cronometer-mcp-version}'
            env:
              # `?? '''` is load-bearing: env is typed { [key]: string }, and a
              # bare process.env ref for an unset variable resolves to undefined,
              # which fails validation and takes the whole boot down rather than
              # just this server. An empty value degrades to an auth failure on
              # the server instead, which failOnStartupError (default false)
              # contains.
              CRONOMETER_USERNAME: !!js process.env.CRONOMETER_USERNAME ?? '''
              CRONOMETER_PASSWORD: !!js process.env.CRONOMETER_PASSWORD ?? '''
              CRONOMETER_ACCOUNT_TZ: Europe/Amsterdam
              UV_PYTHON_DOWNLOADS: never
  '';
in
{
  options.apps.dsh = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Enable DeepSeek Harness (dsh)";
    };

    settings = lib.mkOption {
      type = settingsFormat.type;
      default = { };
      example = lib.literalExpression ''
        {
          noema-memory = {
            command = "noema-mcp";
            recallBudgetTokens = 1200;
          };
        }
      '';
      description = ''
        Declared `$DSH_HOME/settings.yaml` entries, keyed by the namespace each
        plugin registers. Merged into the existing file on activation: declared
        keys win, everything else the web UI wrote is left alone.

        This is the escape hatch for plugins that register their configuration
        through the settings service instead of a Cordis config schema -- those
        cannot be reached from the profile patch at all.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    # Namespaces are whatever each plugin registers with the settings service;
    # `noema-memory` is dsh-noema's, from its names.js. Only `command` is
    # load-bearing -- the Nix build ships no bundled server, so the plugin's
    # `bundled` default finds nothing. The other two are already upstream
    # defaults, pinned because they are decisions rather than accidents:
    # acceptByDefault is what makes noema_remember persist instead of queueing
    # behind the server's `review` write policy, and an explicit noemaRoot beats
    # an implicit ~/.agent-memory when it holds the whole memory store.
    apps.dsh.settings = {
      noema-memory = {
        command = "noema-mcp";
        noemaRoot = "${config.home.homeDirectory}/.agent-memory";
        acceptByDefault = true;
      };
    };

    programs.dsh = {
      enable = true;

      # One profile per interaction face -- the face bundles are mutually
      # exclusive, so they cannot share a tree. Each materializes as
      # $DSH_HOME/profiles/nix-<name>.
      # noema rides on the two interactive faces only: its tools are worth
      # having wherever a conversation continues, but headless is one-shot and
      # would just pay the server spawn. Its settings page is web-only, so the
      # one-time setup below has to happen under nix-web even if the TUI is
      # where it gets used.
      profiles = {
        tui = {
          bundles = [
            pkgs.dsh.bundles.tui
            pkgs.dsh.bundles.noema
          ];
          patch = cordisPatch;
        };
        web = {
          bundles = [
            pkgs.dsh.bundles.web-app
            pkgs.dsh.bundles.noema
          ];
          patch = cordisPatch;
        };
        headless = {
          bundles = [ pkgs.dsh.bundles.headless ];
          patch = cordisPatch;
        };
      };

      # Bare `dsh` boots the TUI. Anything else is `dsh --profile nix-web` etc;
      # the `dsh web` sugar is gone with the old wrapper, since it only ever
      # existed to work around --patch's placement rules.
      defaultProfile = config.programs.dsh.profiles.tui.materializedName;
    };

    # The web face as a systemd user unit instead of a foreground `dsh
    # --profile nix-web`. This is the one path with a real secret story:
    # EnvironmentFile= is read by systemd when the unit starts, so the keys
    # reach dsh without a shell profile, without the store, and without landing
    # in every other process's environment the way the bash exports below do.
    # The TUI cannot use it -- it runs in your terminal, not under systemd --
    # so that face still depends on programs.bash.initExtra.
    #
    # Everything else is upstream's default and already matches this config:
    # `profiles` inherits programs.dsh.profiles, `profile` is "nix-web" (the web
    # profile's materializedName), listenAddress/port are 127.0.0.1:3080, and
    # dataDir resolves to the same $DSH_HOME -- so settings.yaml, the profile
    # trees and the noema store are shared with the TUI rather than forked.
    #
    # autoStart is off: the web face is not in normal use, and an always-on unit
    # is not free. Measured idle cost was ~275 MB RSS across three processes --
    # node, plus a uvx/python mcp-cronometer pair it spawns at boot and holds
    # open forever whether or not anything queries it -- and it binds 3080
    # unauthenticated from login onward, which is a standing agent endpoint with
    # a live API key rather than a foreground process that can be Ctrl-C'd.
    # `systemctl --user start dsh-web` when the web UI is actually wanted.
    #
    # --no-open because the unit inherits the session manager's environment
    # (BROWSER, WAYLAND_DISPLAY are imported there), so every start -- including
    # each Restart=on-failure -- otherwise opens a real Firefox tab.
    #
    # Starting it while `dsh --profile nix-web` runs in the foreground is the
    # EADDRINUSE case; stop one or the other.
    services.dsh = {
      enable = true;
      autoStart = false;
      extraArguments = [ "--no-open" ];
      environmentFile = "/run/secrets/rendered/dsh-env";
    };

    # dsh has no file-based credential path: `!!js` runs in an ESM bundle with
    # no `require`, and dsh-mcp-client has no envFile option, so both the
    # provider keys and the Cronometer pair have to be real environment
    # variables before dsh starts. sops decrypts to /run/secrets at activation;
    # this reads them at shell start.
    #
    # This is the TUI/headless half of the story -- the dsh-web unit above gets
    # the same values through sops.templates."dsh-env" instead. Both derive from
    # the same sops.secrets entries, so there is one source of truth even though
    # there are two delivery paths.
    #
    # A wrapper function rather than exports at shell start: `local -x` scopes
    # each value to this function and its children, so the keys exist for the
    # dsh process tree and nowhere else. Exporting at login instead put a live
    # API key and the Cronometer password into every shell and every child of
    # one -- build tools, npm scripts, anything whose environment ends up in a
    # log, a crash report or a screen share. That is exposure surface, not a
    # privilege boundary: /run/secrets/* is 0400 and owned by this user, so
    # anything running as the user could always read the files directly.
    #
    # `command dsh` bypasses the function, so this covers every face -- bare
    # `dsh` for the TUI and `dsh --profile nix-headless` are the same binary.
    # As with the exports it replaces, this reaches interactive bash only.
    #
    # An already-set value wins, so a var exported by hand for a one-off is not
    # clobbered. ANTHROPIC_API_KEY has no sops.secrets entry yet -- declaring
    # one that does not exist fails activation. The readability guard keeps it
    # unset rather than empty until the secret is added, at which point the
    # anthropic route above starts resolving.
    programs.bash.initExtra = lib.mkAfter ''
      dsh() {
        local pair var file
        for pair in \
          "DEEPSEEK_API_KEY=/run/secrets/deepseek-api-key" \
          "DASHSCOPE_API_KEY=/run/secrets/dashscope-api-key" \
          "CRONOMETER_USERNAME=/run/secrets/cronometer-email" \
          "CRONOMETER_PASSWORD=/run/secrets/cronometer-password" \
          "ANTHROPIC_API_KEY=/run/secrets/anthropic-api-key"
        do
          var=''${pair%%=*}
          file=''${pair#*=}
          if [ -z "''${!var:-}" ] && [ -r "$file" ]; then
            local -x "''${var?}"
            printf -v "$var" '%s' "$(< "$file")"
          fi
        done
        command dsh "$@"
      }
    '';

    # Restores the declared settings on every activation without taking the file
    # over. Runs whether or not dsh has started before: an absent settings.yaml
    # is installed outright, an existing one is merged into.
    home.activation.dshSettings = lib.mkIf (cfg.settings != { }) (
      lib.hm.dag.entryAfter [ "writeBoundary" ] ''
        dsh_settings=${lib.escapeShellArg "${dshHome}/settings.yaml"}
        $DRY_RUN_CMD mkdir -p "$(dirname "$dsh_settings")"
        if [ -e "$dsh_settings" ]; then
          $DRY_RUN_CMD ${lib.getExe pkgs.yq-go} eval-all --inplace \
            'select(fileIndex == 0) * select(fileIndex == 1)' \
            "$dsh_settings" ${settingsFile}
        else
          $DRY_RUN_CMD install -m 0644 ${settingsFile} "$dsh_settings"
        fi
      ''
    );

    # The coach skill drives weather/intervals-icu through the bash tool, which
    # inherits the session PATH -- the old wrapper's runtimeInputs is what this
    # replaces.
    #
    # noema-mcp is the memory server the noema bundle drives. Upstream ships it
    # inside per-platform npm packages, but those carry only a `files: [bin]`
    # manifest with no bin/ -- the binary is staged from a cargo build at
    # release time, which a source build never runs. So the bundle's default
    # `command: 'bundled'` finds nothing, and the server has to be resolved
    # from PATH instead. Set Settings -> Noema Memory -> Server command to
    # `noema-mcp` once; a bare name rather than a store path, so it survives
    # rebuilds (that setting lives in $DSH_HOME, which Nix does not manage).
    home.packages = [
      weather
      intervals-icu
      pkgs.dsh.noema-mcp
    ];
  };
}
