{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.apps.dsh;

  # Kept in step with ../claude-code/cronometer: the same pinned PyPI server,
  # run through uvx against nixpkgs' Python so uv never downloads its own.
  cronometer-mcp-version = "0.2.1";

  settingsFormat = pkgs.formats.yaml { };

  # $DSH_HOME/settings.yaml is mutable state the web UI owns, so this is a
  # merge rather than a copy: `select(fileIndex == 0) * select(fileIndex == 1)`
  # deep-merges the declared file over the live one, so a key nobody declared
  # here (ui-onboarding.welcomeNoticeVersion, anything set from a settings page)
  # survives every rebuild while declared keys are restored.
  dshHome =
    if config.programs.dsh.home != null then
      config.programs.dsh.home
    else
      "${config.home.homeDirectory}/.dsh";

  settingsFile = settingsFormat.generate "dsh-settings.yaml" cfg.settings;

  # Built from ../claude-code's scripts rather than relying on that module
  # having put them on PATH. Same name, same inputs, same text, so Nix resolves
  # these to the very store paths apps.claude-code already builds -- the coach
  # skill keeps working even if claude-code is switched off.
  weather = pkgs.writeShellApplication {
    name = "weather";
    runtimeInputs = with pkgs; [
      curl
      jq
      coreutils
      util-linux
    ];
    text = builtins.readFile ./../claude-code/weather/weather.sh;
  };

  intervals-icu = pkgs.writeShellApplication {
    name = "intervals-icu";
    runtimeInputs = with pkgs; [
      curl
      jq
      coreutils
    ];
    text = builtins.readFile ./../claude-code/intervals-icu.sh;
  };

  # Skills are plain SKILL.md directories, so the whole tree goes to the store
  # and dsh scans it read-only. dsh's own command registry is programmatic
  # (ctx.commands.register, from a plugin) and has no markdown loader, so the
  # claude-code `/coach` command ports to a skill rather than a command.
  skills = ./skills;

  # The declarative seam, now owned by deepseek-harness.nix. A profile composes
  # as: base layer, then the profile's bundles in list order, then this string
  # as the profile's cordis.patch.yml. Nothing is passed at launch any more --
  # the module materializes $DSH_HOME/profiles/nix-<name> from the store and
  # re-syncs it on every activation and every `dsh` run (mode = "managed").
  #
  # This has to be a *profile* patch rather than programs.dsh.patch: the
  # home-level option is typed `listOf attrs` and renders through
  # lib.generators.toYAML, which would quote the `!!js` tags below into inert
  # strings. The profile option also accepts `lines`, and renderPatch passes a
  # string through verbatim, so the tags survive.
  #
  # Two shapes are in play, both verified against --dump-config: a bare `id:`
  # row patches the entry that already exists under that id, and an `insert:`
  # list adds new ones. A patch REPLACES the targeted row's whole `config`, so
  # any row touched here restates every key it means to keep.
  cordisPatch = ''
    # Generated by home/programs/dsh/default.nix -- do not edit in place.

    # The skills system ships disabled in the web profile. tool-skill is the
    # model-facing loader; without it the catalogue is never readable. The tui
    # bundle enables both itself, but this layer applies after it, so stating
    # them here keeps all three profiles identical.
    - id: skill-filesystem
      disabled: false
      config:
        customSkillDirs:
          - ${skills}
    - id: tool-skill
      disabled: false

    # The AGENTS.md/CLAUDE.md workspace loader. Enabled in dsh-base, but the
    # tui bundle turns it off (dsh-tui/cordis.patch.yml:56), so the TUI would
    # otherwise see no project instruction files at all while headless does.
    # It walks the ancestor chain upward from the session workspace rather than
    # reading only the root, so per-project files are picked up the way
    # claude-code does it. maxBytes is restated because a patch replaces the
    # targeted row's whole config.
    - id: agent-instructions
      disabled: false
      config:
        maxBytes: 65536

    # Claude as a model route. pi-ai (the multi-provider layer under
    # dsh-llm-pi-ai) bundles @anthropic-ai/sdk and ships anthropic in its
    # installed catalog, so the route needs no baseURL, protocol or model list
    # -- only where to find the credential. There is no claude-code subagent
    # provider in 0.1.1-rc.2, so this is what "Claude in dsh" means today.
    #
    # The UI writes provider settings into $DSH_HOME/settings.yaml, which
    # resolves ON TOP of this, so adding routes by hand there still works. A
    # missing key surfaces per request as MISSING_CREDENTIAL rather than
    # failing the boot.
    - id: llm-pi-ai
      config:
        providers:
          anthropic:
            apiKeyEnv: ANTHROPIC_API_KEY

    - insert:
        # Cronometer, mirroring ../claude-code/cronometer. Credentials arrive as
        # process env from the session (see programs.bash.initExtra below)
        # rather than being written here: this file is world-readable in
        # /nix/store.
        - id: mcp-cronometer
          name: '@deepseek-ai/dsh-mcp-client'
          config:
            serverName: cronometer
            transport: stdio
            command: ${lib.getExe' pkgs.uv "uvx"}
            args:
              - '--python'
              - '${pkgs.python314}/bin/python3'
              - 'cronometer-api-mcp==${cronometer-mcp-version}'
            env:
              # `?? '''` is load-bearing: env is typed { [key]: string }, and a
              # bare process.env ref for an unset variable resolves to undefined,
              # which fails validation and takes the whole boot down rather than
              # just this server. An empty value degrades to an auth failure on
              # the server instead, which failOnStartupError (default false)
              # contains.
              CRONOMETER_USERNAME: !!js process.env.CRONOMETER_USERNAME ?? '''
              CRONOMETER_PASSWORD: !!js process.env.CRONOMETER_PASSWORD ?? '''
              CRONOMETER_ACCOUNT_TZ: Europe/Amsterdam
              UV_PYTHON_DOWNLOADS: never
  '';
in
{
  options.apps.dsh = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Enable DeepSeek Harness (dsh)";
    };

    settings = lib.mkOption {
      type = settingsFormat.type;
      default = { };
      example = lib.literalExpression ''
        {
          noema-memory = {
            command = "noema-mcp";
            recallBudgetTokens = 1200;
          };
        }
      '';
      description = ''
        Declared `$DSH_HOME/settings.yaml` entries, keyed by the namespace each
        plugin registers. Merged into the existing file on activation: declared
        keys win, everything else the web UI wrote is left alone.

        This is the escape hatch for plugins that register their configuration
        through the settings service instead of a Cordis config schema -- those
        cannot be reached from the profile patch at all.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    # Namespaces are whatever each plugin registers with the settings service;
    # `noema-memory` is dsh-noema's, from its names.js. Only `command` is
    # load-bearing -- the Nix build ships no bundled server, so the plugin's
    # `bundled` default finds nothing. The other two are already upstream
    # defaults, pinned because they are decisions rather than accidents:
    # acceptByDefault is what makes noema_remember persist instead of queueing
    # behind the server's `review` write policy, and an explicit noemaRoot beats
    # an implicit ~/.agent-memory when it holds the whole memory store.
    apps.dsh.settings = {
      noema-memory = {
        command = "noema-mcp";
        noemaRoot = "${config.home.homeDirectory}/.agent-memory";
        acceptByDefault = true;
      };
    };

    programs.dsh = {
      enable = true;

      # One profile per interaction face -- the face bundles are mutually
      # exclusive, so they cannot share a tree. Each materializes as
      # $DSH_HOME/profiles/nix-<name>.
      # noema rides on the two interactive faces only: its tools are worth
      # having wherever a conversation continues, but headless is one-shot and
      # would just pay the server spawn. Its settings page is web-only, so the
      # one-time setup below has to happen under nix-web even if the TUI is
      # where it gets used.
      profiles = {
        tui = {
          bundles = [
            pkgs.dsh.bundles.tui
            pkgs.dsh.bundles.noema
          ];
          patch = cordisPatch;
        };
        web = {
          bundles = [
            pkgs.dsh.bundles.web-app
            pkgs.dsh.bundles.noema
          ];
          patch = cordisPatch;
        };
        headless = {
          bundles = [ pkgs.dsh.bundles.headless ];
          patch = cordisPatch;
        };
      };

      # Bare `dsh` boots the TUI. Anything else is `dsh --profile nix-web` etc;
      # the `dsh web` sugar is gone with the old wrapper, since it only ever
      # existed to work around --patch's placement rules.
      defaultProfile = config.programs.dsh.profiles.tui.materializedName;
    };

    # dsh has no file-based credential path: `!!js` runs in an ESM bundle with
    # no `require`, and dsh-mcp-client has no envFile option, so both the
    # provider keys and the Cronometer pair have to be real environment
    # variables before dsh starts. sops decrypts to /run/secrets at activation;
    # this reads them at shell start.
    #
    # ANTHROPIC_API_KEY has no sops.secrets entry yet -- declaring one that does
    # not exist fails activation. The readability guard keeps it dormant until
    # the secret is added, at which point the anthropic route above starts
    # resolving.
    programs.bash.initExtra = lib.mkAfter ''
      dsh_export_secret() {
        local var="$1" file="$2"
        if [ -z "''${!var:-}" ] && [ -r "$file" ]; then
          printf -v "$var" '%s' "$(< "$file")"
          export "''${var?}"
        fi
      }

      dsh_export_secret DEEPSEEK_API_KEY    /run/secrets/deepseek-api-key
      dsh_export_secret CRONOMETER_USERNAME /run/secrets/cronometer-email
      dsh_export_secret CRONOMETER_PASSWORD /run/secrets/cronometer-password
      dsh_export_secret ANTHROPIC_API_KEY   /run/secrets/anthropic-api-key

      unset -f dsh_export_secret
    '';

    # Restores the declared settings on every activation without taking the file
    # over. Runs whether or not dsh has started before: an absent settings.yaml
    # is installed outright, an existing one is merged into.
    home.activation.dshSettings = lib.mkIf (cfg.settings != { }) (
      lib.hm.dag.entryAfter [ "writeBoundary" ] ''
        dsh_settings=${lib.escapeShellArg "${dshHome}/settings.yaml"}
        $DRY_RUN_CMD mkdir -p "$(dirname "$dsh_settings")"
        if [ -e "$dsh_settings" ]; then
          $DRY_RUN_CMD ${lib.getExe pkgs.yq-go} eval-all --inplace \
            'select(fileIndex == 0) * select(fileIndex == 1)' \
            "$dsh_settings" ${settingsFile}
        else
          $DRY_RUN_CMD install -m 0644 ${settingsFile} "$dsh_settings"
        fi
      ''
    );

    # The coach skill drives weather/intervals-icu through the bash tool, which
    # inherits the session PATH -- the old wrapper's runtimeInputs is what this
    # replaces.
    #
    # noema-mcp is the memory server the noema bundle drives. Upstream ships it
    # inside per-platform npm packages, but those carry only a `files: [bin]`
    # manifest with no bin/ -- the binary is staged from a cargo build at
    # release time, which a source build never runs. So the bundle's default
    # `command: 'bundled'` finds nothing, and the server has to be resolved
    # from PATH instead. Set Settings -> Noema Memory -> Server command to
    # `noema-mcp` once; a bare name rather than a store path, so it survives
    # rebuilds (that setting lives in $DSH_HOME, which Nix does not manage).
    home.packages = [
      weather
      intervals-icu
      pkgs.dsh.noema-mcp
    ];
  };
}
