{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.apps.dsh;

  dsh = pkgs.callPackage ./../../../pkgs/dsh { };

  # Kept in step with ../claude-code/cronometer: the same pinned PyPI server,
  # run through uvx against nixpkgs' Python so uv never downloads its own.
  cronometer-mcp-version = "0.2.1";

  # Built from ../claude-code's scripts rather than relying on that module
  # having put them on PATH. Same name, same inputs, same text, so Nix resolves
  # these to the very store paths apps.claude-code already builds -- the coach
  # skill keeps working even if claude-code is switched off.
  weather = pkgs.writeShellApplication {
    name = "weather";
    runtimeInputs = with pkgs; [
      curl
      jq
      coreutils
      util-linux
    ];
    text = builtins.readFile ./../claude-code/weather/weather.sh;
  };

  intervals-icu = pkgs.writeShellApplication {
    name = "intervals-icu";
    runtimeInputs = with pkgs; [
      curl
      jq
      coreutils
    ];
    text = builtins.readFile ./../claude-code/intervals-icu.sh;
  };

  # Skills are plain SKILL.md directories, so the whole tree goes to the store
  # and dsh scans it read-only. dsh's own command registry is programmatic
  # (ctx.commands.register, from a plugin) and has no markdown loader, so the
  # claude-code `/coach` command ports to a skill rather than a command.
  skills = ./skills;

  # The declarative seam. A profile composes as: bundle layers, then the
  # profile's own cordis.patch.yml, then --patch overlays. Only the last is
  # ours -- $DSH_HOME/profiles/ is mutable state the web UI and `dsh plugin`
  # both write, so Home Manager stays out of it entirely and this store-path
  # overlay lands on top instead.
  #
  # Two shapes are in play, both verified against --dump-config: a bare `id:`
  # row patches the entry that already exists under that id, and an `insert:`
  # list adds new ones. A patch REPLACES the targeted row's whole `config`, so
  # any row touched here restates every key it means to keep.
  cordisPatch = pkgs.writeText "dsh-cordis.patch.yml" ''
    # Generated by home/programs/dsh/default.nix -- do not edit in place.

    # The skills system ships disabled in the web profile. tool-skill is the
    # model-facing loader; without it the catalogue is never readable.
    - id: skill-filesystem
      disabled: false
      config:
        customSkillDirs:
          - ${skills}
    - id: tool-skill
      disabled: false

    # Claude as a model route. pi-ai (the multi-provider layer under
    # dsh-llm-pi-ai) bundles @anthropic-ai/sdk and ships anthropic in its
    # installed catalog, so the route needs no baseURL, protocol or model list
    # -- only where to find the credential. There is no claude-code subagent
    # provider in 0.1.1-rc.2, so this is what "Claude in dsh" means today.
    #
    # The base layer is the right home for it: the UI writes provider settings
    # into $DSH_HOME/settings.yaml, which resolves ON TOP of this, so adding
    # routes by hand there still works. A missing key surfaces per request as
    # MISSING_CREDENTIAL rather than failing the boot.
    - id: llm-pi-ai
      config:
        providers:
          anthropic:
            apiKeyEnv: ANTHROPIC_API_KEY

    - insert:
        # Cronometer, mirroring ../claude-code/cronometer. Credentials arrive as
        # process env from the wrapper below rather than being written here:
        # this file is world-readable in /nix/store.
        - id: mcp-cronometer
          name: '@deepseek-ai/dsh-mcp-client'
          config:
            serverName: cronometer
            transport: stdio
            command: ${lib.getExe' pkgs.uv "uvx"}
            args:
              - '--python'
              - '${pkgs.python314}/bin/python3'
              - 'cronometer-api-mcp==${cronometer-mcp-version}'
            env:
              # `?? '''` is load-bearing: env is typed { [key]: string }, and a
              # bare process.env ref for an unset variable resolves to undefined,
              # which fails validation and takes the whole boot down rather than
              # just this server. An empty value degrades to an auth failure on
              # the server instead, which failOnStartupError (default false)
              # contains.
              CRONOMETER_USERNAME: !!js process.env.CRONOMETER_USERNAME ?? '''
              CRONOMETER_PASSWORD: !!js process.env.CRONOMETER_PASSWORD ?? '''
              CRONOMETER_ACCOUNT_TZ: Europe/Amsterdam
              UV_PYTHON_DOWNLOADS: never
  '';

  # Secrets are read from /run/secrets at launch and handed to dsh as process
  # env, the same shape intervals-icu.sh uses. dsh resolves the DeepSeek key
  # through `apiKeyEnv`, which defaults to DEEPSEEK_API_KEY, so no provider
  # config is needed for it at all. dsh-mcp-client scrubs the ambient env
  # before spawning a server, which is why the Cronometer pair is forwarded
  # explicitly by the `!!js process.env.*` refs in the patch above.
  dsh-wrapped = pkgs.writeShellApplication {
    name = "dsh";
    # weather and intervals-icu ride on PATH because the coach skill drives them
    # through the bash tool, exactly as the claude-code command does.
    runtimeInputs = [
      pkgs.coreutils
      weather
      intervals-icu
    ];
    text = ''
      export_secret() {
        local var="$1" file="$2"
        if [ -z "''${!var:-}" ] && [ -r "$file" ]; then
          printf -v "$var" '%s' "$(cat "$file")"
          export "''${var?}"
        fi
      }

      export_secret DEEPSEEK_API_KEY    /run/secrets/deepseek-api-key
      export_secret CRONOMETER_USERNAME /run/secrets/cronometer-email
      export_secret CRONOMETER_PASSWORD /run/secrets/cronometer-password

      # Not declared in sops.secrets yet -- there is no anthropic key in
      # secrets.yaml, and declaring one that does not exist fails activation.
      # The readability guard above makes this dormant until the secret is
      # added, at which point the anthropic route in the patch starts resolving.
      export_secret ANTHROPIC_API_KEY   /run/secrets/anthropic-api-key

      # --patch is a launcher flag, and the launcher is picky about where it may
      # appear. `dsh web` is sugar for `--profile web` and rejects any parent
      # launcher flag outright, so the sugar has to be unwrapped before the flag
      # can be added. `dsh plugin` forwards its tail to pnpm and takes no patch
      # at all.
      case "''${1-}" in
        web | headless | tui)
          profile="$1"
          shift
          exec ${lib.getExe dsh} --profile "$profile" --patch ${cordisPatch} "$@"
          ;;
        plugin)
          exec ${lib.getExe dsh} "$@"
          ;;
        *)
          exec ${lib.getExe dsh} --patch ${cordisPatch} "$@"
          ;;
      esac
    '';
  };
in
{
  options.apps.dsh = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Enable DeepSeek Harness (dsh)";
    };
  };

  config = lib.mkIf cfg.enable {
    home.packages = [ dsh-wrapped ];
  };
}
